BRACKET_TYPE_CHAMPIONSHIP = "championship"
BRACKET_TYPE_CONSOLATION = "consolation"

GAME_TYPE_REGULAR = "REGULAR"
GAME_TYPE_PLAYOFF = "PLAYOFF"
GAME_TYPE_CONSOLATION = "CONSOLATION"

STORAGE_JSON = "json"
STORAGE_AIRTABLE = "airtable"

DATA_TYPE_GAMES = "games"
DATA_TYPE_TEAMS = "teams"