# TODO delete
AIRTABLE_API_KEY = None
AIRTABLE_BASE_TEAMS_ID = None
AIRTABLE_BASE_GAMES_ID = None

JSON_TEAMS_JSON_FILE = "teams.json"
JSON_SCHEDULE_JSON_FILE = "schedule.json"

GAME_TYPE_REGULAR = "REGULAR"
GAME_TYPE_PLAYOFF = "PLAYOFF"
GAME_TYPE_CONSOLATION = "CONSOLATION"
