NFL_FF_LEAGUE_ACTIVE_YEARS = [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]

AIRTABLE_API_KEY = None
AIRTABLE_BASE_TEAMS_ID = None
AIRTABLE_BASE_GAMES_ID = None
# AIRTABLE_API_KEY = os.environ["AIRTABLE_API_KEY"]
# AIRTABLE_BASE_TEAMS_ID = os.environ["AIRTABLE_BASE_TEAMS_ID"]
# AIRTABLE_BASE_GAMES_ID = os.environ["AIRTABLE_BASE_GAMES_ID"]

BACKENDS_JSON = "json"
BACKENDS_AIRTABLE = "airtable"
BACKENDS = [BACKENDS_JSON, BACKENDS_AIRTABLE]

JSON_TEAMS_JSON_FILE = "teams.json"
JSON_SCHEDULE_JSON_FILE = "schedule.json"
