import os

NFL_FF_LEAGUE_ID = os.environ["NFL_FF_LEAGUE_ID"]
NFL_FF_LEAGUE_ACTIVE_YEARS = [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]

AIRTABLE_API_KEY = os.environ["AIRTABLE_API_KEY"]
AIRTABLE_BASE_TEAMS_ID = os.environ["AIRTABLE_BASE_TEAMS_ID"]
AIRTABLE_BASE_GAMES_ID = os.environ["AIRTABLE_BASE_GAMES_ID"]

JSON_TEAMS_JSON_FILE = "teams.json"
JSON_SCHEDULE_JSON_FILE = "schedule.json"
